# EGO Facebook

In [2]:
import math, subprocess
import numpy as np
import pandas as pd
import time
import matplotlib.pyplot as plt
import os

# Item 3.1
## Con los datos de Facebook, computar la matriz de similaridad con producto interno de la matriz de atributos

In [14]:
def calcular_matriz_similaridad(mat1):
    return np.dot(mat1, np.transpose(mat1))

In [32]:
# Levantamos la matriz
f = open("../tests/ego-facebook.feat", "r")
lineas = []
for linea in f:
    lineas.append([int(i) for i in linea.split(" ")])
nodes = [linea[0] for linea in lineas]
attributes = np.matrix([linea[1:] for linea in lineas])

matriz_similaridad = calcular_matriz_similaridad(attributes)
matriz_similaridad = matriz_similaridad / np.max(matriz_similaridad)
umbral = 0.5
conexiones_calculadas = (matriz_similaridad > umbral).astype(int)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
